[package]
name = "zql-conformance-host"
version = "0.1.0"
edition = "2021"
publish = false
license = "Apache-2.0"

[lib]
path = "runner/lib.rs"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "zql-native"
path = "runner/main.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
zega = { git = "https://github.com/zegadb/zega.git", rev = "a0dd28e75b7bb373c2e1890547b6508c9f47c656" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"

[profile.dev]
debug = 0

[profile.release]
opt-level = "s"
lto = true
